### ISSUE TITLE
班级终端：取得服务安装信息

### ISSUE THREAD

**Issue by StarWishsama** [yunzhubanban/server#2]
## 功能描述

班级终端 在填写 服务器地址 后取得服务安装信息

### 请求参数

无

### 期望返回

time：当前时间（秒级时间戳）
name：学校

其中 `name` 是在 配置文件 中定义的

## 追踪

- [x] 准备就绪
- [x] 开发完毕

**Comment by qianjunakasumi** [comment]
@StarWishsama 内容已更新，请注意

**Comment by qianjunakasumi** [comment]
审查完毕 By @qianjunakasumi 
准许合并（

**Comment by qianjunakasumi** [comment]
https://github.com/yunzhubanban/server/compare/ae37659..ff3248d

**Comment by qianjunakasumi** [comment]
开发完毕
